const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    TOGGLE_PRODUCT_DETAILS: 'TOGGLE_PRODUCT_DETAILS',
    SELECTED_ELEMENT: 'SELECTED_ELEMENT',
    TOGGLE_ORDER_FORM: 'TOGGLE_ORDER_FORM',
    TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',
    MESSAGE_MESSAGE: 'MESSAGE_MESSAGE'
}

export default ShopActionTypes