const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    TOGGLE_PRODUCT_DETAILS: 'TOGGLE_PRODUCT_DETAILS',
    SELECTED_ELEMENT: 'SELECTED_ELEMENT'
}

export default ShopActionTypes