const ComenziActionTypes = {
    FETCH_COMENZINOI: 'FETCH_COMENZINOI',
    FETCH_COMENZIPROCESATE: 'FETCH_COMENZIPROCESATE',
    FETCH_COMENZIPRODUSE: 'FETCH_COMENZIPRODUSE'
}

export default ComenziActionTypes